{
 "title": "Simulation engine",
 "time": { "from": "2000-01-01T00:00:00.000Z", "to": "2000-01-01T00:11:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "simulation_id",
    "label": "Simulation ID",
    "query": "1676532689-f236a050-57bc-47f5-852f-f10d9564a621"
   },
   {
    "name": "run",
    "label": "Run",
    "query": "simkit\n| where name == 'simkit_time_delays_pending'\n| where simulation_id == '$simulation_id'\n| project run = tostring(run)"
   }
  ]
 },
 "panels": [
  {
   "title": "Tick duration",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "feb23",
     "expression": {
      "from": { "property": { "name": "demo1", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "simkit\n| where name == 'simkit_time_elapsed_ticks_total'\n| where simulation_id == '$simulation_id' and $__contains(run, $run)\n| where value > 0\n| join (simkit\n  | where name == 'simkit_time_elapsed_seconds_total'\n  | project simulation_id, timestamp, seconds_value = value\n  ) on simulation_id, timestamp\n| where seconds_value > 0\n| project tick_duration_seconds = seconds_value / value, timestamp\n| summarize tick_duration_seconds = avg(tick_duration_seconds)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Ticks per second",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "feb23",
     "expression": {
      "from": { "property": { "name": "demo1", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "simkit\n| where name == 'simkit_time_elapsed_ticks_total'\n| where simulation_id == '$simulation_id' and $__contains(run, $run)\n| where value > 0\n| join (simkit\n  | where name == 'simkit_time_elapsed_seconds_total'\n  | project simulation_id, timestamp, seconds_value = value\n  ) on simulation_id, timestamp\n| where seconds_value > 0\n| project ticks_per_second = value / seconds_value, timestamp\n| summarize ticks_per_second = avg(ticks_per_second)",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Scheduling operations in progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "database": "feb23",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "simkit\n| where $__timeFilter(timestamp)\n| where name in ('simkit_time_delays_pending', 'simkit_time_synchronous_timers_current', 'simkit_time_asynchronous_timers_current')\n| where simulation_id == '$simulation_id' and $__contains(run, $run)\n| summarize value = avg(value) by bin(timestamp, $__timeInterval), name\n| order by timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "New scheduling operations (1/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "database": "feb23",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "// Calculates the rate of change per second per bin, given a series of incrementing value + timestamp bins.\nlet series_rate=(values:dynamic, timestamps:dynamic) {\n  let values_delta = series_subtract(array_shift_left(values, 1), values);\n  let timestamps_delta_ticks = series_subtract(array_shift_left(timestamps, 1), timestamps);\n  let timestamps_delta_seconds = series_divide(timestamps_delta_ticks, repeat(10000000, array_length(timestamps)));\n  series_divide(values_delta, timestamps_delta_seconds)\n};\n\nsimkit\n| where $__timeFilter(timestamp)\n| where name in ('simkit_time_synchronous_timers_total', 'simkit_time_asynchronous_timers_total', 'simkit_time_delays_total')\n| where simulation_id == '$simulation_id' and $__contains(run, $run)\n| partition by name\n(\n  sort by timestamp asc\n  | make-series values=min(value), timestamps=min(timestamp) on timestamp step $__timeInterval by name\n  | extend values_delta_per_second = series_rate(values, timestamps)\n)\n// Names that make Grafana output functional and pretty enough.\n| project Timestamp = timestamp, ['­'] = values_delta_per_second, name\n| order by name asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Usage instructions",
   "type": "text",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 3 },
   "options": {
    "content": "1. Take metrics.json.gz from simulator.\r\n1. Upload to Azure Data Explorer, simkit table.\r\n1. Paste simulation ID into textbox.\r\n\r\nSimulations start on 2000-01-01 00:00:00 UTC by convention.\r\n\r\nError SEM0025 typically means \"simulation not found\"."
   },
   "targets": [
    {
     "database": "feb23",
     "expression": {
      "from": { "property": { "name": "test2", "type": "string" }, "type": "property" },
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "test2\n| where $__timeFilter(timestamp)\n| order by timestamp asc",
     "querySource": "raw"
    }
   ]
  },
  {
   "title": "Timer callbacks (1/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "database": "feb23",
     "expression": {
      "groupBy": {
       "expressions": [],
       "type": "and"
      },
      "reduce": {
       "expressions": [],
       "type": "and"
      },
      "where": {
       "expressions": [],
       "type": "and"
      }
     },
     "query": "// Calculates the rate of change per second per bin, given a series of incrementing value + timestamp bins.\nlet series_rate=(values:dynamic, timestamps:dynamic) {\n  let values_delta = series_subtract(array_shift_left(values, 1), values);\n  let timestamps_delta_ticks = series_subtract(array_shift_left(timestamps, 1), timestamps);\n  let timestamps_delta_seconds = series_divide(timestamps_delta_ticks, repeat(10000000, array_length(timestamps)));\n  series_divide(values_delta, timestamps_delta_seconds)\n};\n\nsimkit\n| where $__timeFilter(timestamp)\n| where name == 'simkit_time_timer_callback_total'\n| where simulation_id == '$simulation_id' and $__contains(run, $run)\n| partition by run\n(\n  // NB! Interval must not be smaller than our measurement interval or you'll get some empty bins.\n  make-series values=min(value), timestamps=min(timestamp) on timestamp step $__timeInterval by run\n  | extend values_delta_per_second = series_rate(values, timestamps)\n)\n// Names that make Grafana output functional and pretty enough.\n| project Timestamp = timestamp, ['­'] = values_delta_per_second, run = strcat('Run ', run)\n| order by run asc",
     "querySource": "raw"
    }
   ]
  }
 ]
}