name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-restore --verbosity normal
    - name: Get timestamp
      id: timestamp
      run: echo "::set-output name=timestamp::$(date +'%Y%m%d%H%M%S')"
    - name: Package
      run: dotnet pack --configuration Release --version-suffix pre-${{ steps.timestamp.outputs.timestamp }}
    - uses: actions/upload-artifact@v2
      with:
        name: nupkg
        path: '*.nupkg'
    # - name: Publish
    #   run: nuget push -ApiKey ${{ secrets.nuget_api_key }} -Source https://api.nuget.org/v3/index.json *.nupkg